[package]
name = "acp"
version = "0.1.0"
authors = ["rafi"]
edition = "2018"

[lib]
name = "libacp"
path = "src/lib/lib.rs"

[[bin]]
name = "acp"
path = "src/client/main.rs"

[[bin]]
name = "acpd"
path = "src/server/main.rs"

[dependencies]
bytes = "1.0.1"
prost = "0.7.0"
tokio = { version = "1.1.1", features = ["full"] }

[build-dependencies]
prost-build = "0.7.0"